# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_63sx2rgmje\clone\recipe, last modified Wed May 10 12:01:53 2023
# ------------------------------------------------

package:
  name: libffi
  version: 3.4.4
source:
  patches:
    - 0002-Don-t-define-FFI_COMPLEX_TYPEDEF-ifndef-FFI_TARGET_H.patch
    - fix_w3264_masm.patch
    - win_cmake.patch
  sha256: d66c56ad259a82cf2a9dfc408b32bf5da52371500b84745f7fb8b645712df676
  url: https://github.com/libffi/libffi/releases/download/v3.4.4/libffi-3.4.4.tar.gz
build:
  number: '0'
  run_exports:
    - libffi >=3.4,<4.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  requires:
    - cmake
    - llvm-tools
    - m2-grep
    - vs2017_win-64
  source_files:
    - testsuite
    - testsuite/libffi.bhaible
about:
  description: 'The libffi library provides a portable, high level programming interface

    to various calling conventions. This allows a programmer to call any

    function specified by a call interface description at run-time.

    '
  dev_url: https://github.com/libffi/libffi
  doc_url: https://sourceware.org/libffi/
  home: https://sourceware.org/libffi/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Portable Foreign Function Interface Library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 63b9d137-480a-49f0-9e56-ca3ac0161b3d
  recipe-maintainers:
    - isuruf
    - scopatz
    - stefan-balke
  remote_url: git@github.com:AnacondaRecipes/libffi-feedstock.git
  sha: 51c485b94e09cdd4bd6550dea0c5bd0b06a8488a
