# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_175uxv22v0\clone\recipe, last modified Tue Sep 26 16:26:01 2023
# ------------------------------------------------

package:
  name: wheel
  version: 0.41.2
source:
  sha256: 0c5ac5ff2afb79ac23ab82bab027a0be7b5dbcf2e54dc50efe4bf507de1f7985
  url: https://pypi.io/packages/source/w/wheel/wheel-0.41.2.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  string: py311haa95532_0
requirements:
  host:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - flit-core 3.9.0 py311haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.11 h2bbff1b_2
    - python 3.11.5 he1021f5_0
    - python-installer 0.6.0 py311haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - python >=3.11,<3.12.0a0
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 176553a8-9ec9-4187-b9bf-3291f95efd71
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/wheel-feedstock.git
  sha: ffe9b970a7613cc6a8919a1cb79f3b3f4ed764dc
  skip-lints:
    - missing_wheel
